### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cuamckuu** [cuamckuu/daily-better#1]
# Основные требования

- [x] Наличие юзеров
- [ ] Сохранение закладок в одном месте
- [x] Наличие API для интеграций
- [ ] Бот в телеграме для быстрого добавления в закладки и получения ссылок обратно
- [ ] Автозагрузка названия и превью по одной ссылке
- [ ] Отметки о прочтении 
- [ ] Папки/теги для закладок
- [ ] Листы закладок
- [ ] Поддержка пользователей и нескольких списков закладок у них
- [ ] Сохранение через bookmarklet

# Дополнительные требования

- [ ] Возможность экспорта из браузера
- [ ] Расширение для браузеров
- [ ] Рекомендация контента, для начала случайная закладка в день, потом условно простые статьи и видео выдаются в приоритете
- [ ] Оценка объёма, длины видео, числа ссылок, и т. д.
- [ ] Автоопределение папки/тега
- [ ] Рейтинг прочитанных
- [ ] Несколько режимов работы: n закладок в день, бесконечная случайная лента, и т.д.
- [ ] Поддержка публичных и приватных списков закладок
- [ ] Автосбор всякой метаинформации, например есть ли на сайте видео, есть ли аудио, удобно ли читать с телефона, и т. д.
- [ ] Сохранение оффлайн версий страниц, на случай их смерти
- [ ] Мб режим чтения, если мы будем вытаскивать содержимое и считать его длину, можно сразу выдавать то же содержимое в удобной читалке, но это не в приоритете
- [ ] Добавление описания к закладкам и к спискам закладок
- [ ] Мб перегон содержимого между разными форматами, если это видео/аудио, перегоняем в текст, если текст, ищем аудиоверсию или озвучиваем говорилкой
- [ ] Обработчики определённых сайтов, если это ютуб, вытаскиваем инфу про видео, если амазон, отзывы и рейтинг книги, и т. д.
- [ ] Возможность экспорта всего, что насохранял пользователь, например в json
- [ ] Оффлайн режим работы, в приоритете чтение
- [ ] Если будет непубличная статья, нужно подумать, как сохранять её, с ПК примерно понятно, можно просто сохранить html, с телефоном сильно проблемнее
- [ ] Экспорт всех ссылок из выделенного/вставленного текста или html страницы
- [ ] Запоминать даты добавления и выставления оценки
- [ ] Рекомендации с учётом потребностей, условно мини тест: Хотите учиться/развлечься? Сколько готовы потратить времени?  Предпочитаемый формат? 
- [ ] Т. к. когда-то будут публичные доски, возможно стоит делать рейтинг и для досок
- [ ] Мб завести раздельные оценки, как на metacritic, отдельно оценка владельца, и отдельно оценка всех остальных
- [ ] Круто, если получится рекомендательная система контента, условно объединение ленты ютуба, вк, гугла, итд
- [ ] Подписка на чужие списки
- [ ] Копирование чужих списков
- [ ] Выдача "дейли квестов" и отслеживание прогресса
- [ ] Поиск по названиям и ссылкам, мб полнотекстовой поиск
- [ ] Возможность сохранения файлов, например pdf
- [ ] Возможность выделения цитат
- [ ] Экспорт открытых вкладок или закладок из мобилки, проще всего это сделать через дебаг по usb.
- [ ] Прогресс чтения/просмотра, например для видео или больших статей
- [ ] Генерация TLDR и/или Summary
- [ ] Отображение связанных закладок, например с одного сайта
- [ ] Отображения графа связей закладок, мб кластеризация
